### ISSUE TITLE
drivers?

### ISSUE THREAD

**Issue by jay-hd** [WoeUSB/WoeUSB-ng#102]
This may not be an issue with woe but here goes anyway. I got Windows on to a usb but when i went to install it said i dont have the drivers? I downloaded the iso from the microsoft site. Why would that download not include the drivers?

**Comment by gwbischof** [comment]
I have the same issue

**Comment by Weissstreifen** [comment]
Same issues here, original ISO from MS. Tried woeusb and ventoy. Same result. Missing media drivers so the installation can't start.

**Comment by brlin-tw** [comment]
Pro-tip: Provide a screenshot of the problems that you are experiencing may increase your troubleshooting chances.

A probable guess is that the installation media doesn't ship the drivers of your system's storage controller, which may be possible for new hardware, you'll need to grab the driver from the system manufacturer's website, store it in a flash drive or compact disc, and load it manually during the "Where to install the Windows system to" dialogue so that your storage devices can be enumerated.

Doesn't seem to be a WoeUSB(/-ng) issue anyway, closing.
