### ISSUE TITLE
Patched core.py

### ISSUE THREAD

**Issue by meow-watermelon** [WoeUSB/WoeUSB-ng#64]
Hi,

I'm not sure if it's useful for others but I fixed some glitches I found in the original `core.py`:

1. Removed pseudo progress bar feature. WoeUSB-NG uses a timer progress bar which actually does not show actual progress which is just a decoration.
2. Switched buffered write to sync-IO write. WoeUSB-NG uses buffered write to write Windows files to the USB disk. This would cause potential disk loss issues and would take a longer time when OS initiates write-back.
3. Added additional writing progress information to show the actual data writing process. This is useful for users to understand how much data is written already in the USB disk rather than pseudo progress data.

The patched version is here: https://github.com/meow-watermelon/woeusb-ng-patches 

If you think it's useful, I will raise a PR for a permanent fix.

Thanks.

**Comment by WaxyMocha** [comment]
Every improvement is welcomed, go ahead with PR

**Comment by brlin-tw** [comment]
> I will raise a PR for a permanent fix.

Individual PRs for each separatable change would be more welcomed, as it will speed up the review process.

**Comment by meow-watermelon** [comment]
Thanks, @WaxyMocha and @brlin-tw. PR raised: https://github.com/WoeUSB/WoeUSB-ng/pull/65

**Comment by WaxyMocha** [comment]
`1. Removed pseudo progress bar feature. WoeUSB-NG uses a timer progress bar which actually does not show actual progress which is just a decoration.`
What timer? It looks up the size of target directory every 50 ms and prints how much data was copied. It even shows "Copied x form a total of y"

`2. Switched buffered write to sync-IO write. WoeUSB-NG uses buffered write to write Windows files to the USB disk. This would cause potential disk loss issues and would take a longer time when OS initiates write-back.`
No, if drive gets unmounted then all data is flushed to the drive, you risk data loss if you remove drive before program exits.

`3. Added additional writing progress information to show the actual data writing process. This is useful for users to understand how much data is written already in the USB disk rather than pseudo progress data.`
Currently there is a helper function that converts bytes to mega/giga bytes, because showing 6/9 digit numbers is confusing for a user, also your implementation shows progress per file, and I'm not getting how that is better from what we have now.

I'm closing this issue and your PR, as the premise from changes is, in my honest opinion, just wrong.
Thank you for your contribution anyways.
